<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>annotations</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\Silmoon.AI\Silmoon.AI.Client\Silmoon.AI.Client.csproj" />
    <ProjectReference Include="..\..\Silmoon.AI\Silmoon.AI.Tools\Silmoon.AI.Tools.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.CodeAnalysis.CSharp.Scripting" Version="5.3.0" />
  </ItemGroup>


</Project>
